version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2023.04.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "image-train-filters-app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: make dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "image-train-filters-app/build.gradle" }}
      - run:
          name: Run Tests
          command: make lint
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: image-train-filters-app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: image-train-filters-app/build/test-results
